---
title: "clean_data"
author: "Austin Kennedy"
date: "1/12/2022"
output: html_document
---

```{r Clear memory and setup}
rm(list=ls())
options(scipen=999)
```

```{r Load Packages}
library(tidyverse)
library(fixest)
library(modelsummary)
library(kableExtra)
library(lubridate)
```

```{r Load Data}
odi_ind <- read.csv("../Temporary/odi_fdi.csv")
# odi_fdi_safety <- read.csv("../Temporary/odi_fdi_safety.csv")
# odi_source <- read.csv("../Temporary/odi_fdi_source.csv")
fdi <- read.csv("../Temporary/fdi_country_year.csv")
odi_sum <- read.csv("../Temporary/odi_sum.csv")
odi_plant <- read.csv("../Temporary/odi_plant.csv")
ind_year <- read.csv("../Temporary/industry_agg.csv")
state_ind_year <- read.csv("../Temporary/state_industry_agg.csv")
```

```{r Industry-detailed regressions}
mod1 <- feols(tcr ~ log(fdi),odi_ind, cluster = c("Year", "industry"))
mod2 <- feols(tcr ~ log(fdi) + 0|Year, odi_ind, cluster = c("Year", "industry"))
mod3 <- feols(tcr ~ log(fdi)|Year + industry, odi_ind, cluster = c("Year", "industry"))
mod4 <- feols(tcr ~ log(fdi_tot), odi_plant, cluster = c("Year", "naics_3"))
mod5 <- feols(tcr ~ log(fdi_tot)|Year, odi_plant, cluster = c("Year", "naics_3"))
mod6 <- feols(tcr ~ log(fdi_tot)|Year + naics_3, odi_plant, cluster = c("Year", "naics_3"))
ind_models <- list(mod1, mod2, mod3, mod4, mod5, mod6)
```

```{r Industry lags}
lmod1 <-feols(tcr ~ log(fdi_l1)|Year + industry, odi_ind, cluster = c("Year", "industry"))
lmod2 <-feols(tcr ~ log(fdi_l2)|Year + industry, odi_ind, cluster = c("Year", "industry"))
lmod3 <-feols(tcr ~ log(fdi_l3)|Year + industry, odi_ind, cluster = c("Year", "industry"))
lmod4 <-feols(tcr ~ log(fdi_l4)|Year + industry, odi_ind, cluster = c("Year", "industry"))


lmods <- list(lmod1, lmod2, lmod3, lmod4)
```

```{r Weighted Avg Regressions}
wa_mod1 <- feols(tcr ~ log(fdi_tot)*weight_avg, odi_plant, cluster = c("Year", "naics_3"))
wa_mod2 <- feols(tcr ~ log(fdi_tot)*weight_avg|Year, odi_plant, cluster = c("Year", "naics_3"))
wa_mod3 <- feols(tcr ~ log(fdi_tot)*weight_avg|Year + naics_3, odi_plant, cluster = c("Year", "naics_3"))

wa_models <- list(wa_mod1, wa_mod2, wa_mod3)
```

```{r Weighted Avg lags}
lwa_mod1 <- feols(tcr ~ log(fdi_tot) + log(weight_avg_l1)|Year + naics_3, odi_plant, cluster = c("Year", "naics_3"))
lwa_mod2 <- feols(tcr ~ log(fdi_tot) + log(weight_avg_l2)|Year + naics_3, odi_plant, cluster = c("Year", "naics_3"))
lwa_mod3 <- feols(tcr ~ log(fdi_tot) + log(weight_avg_l3)|Year + naics_3, odi_plant, cluster = c("Year", "naics_3"))
lwa_mod4 <- feols(tcr ~ log(fdi_tot) + log(weight_avg_l4)|Year + naics_3, odi_plant, cluster = c("Year", "naics_3"))

lwa_mods <- list(lwa_mod1, lwa_mod2, lwa_mod3, lwa_mod4)

```

```{r Deviation Regressions}

d_mod1 <- feols(tcr ~ davg, odi_plant, cluster = c("Year", "naics_3"))
d_mod2 <- feols(tcr ~ davg|Year, odi_plant, cluster = c("Year", "naics_3"))
d_mod3 <- feols(tcr ~ davg|naics_3, odi_plant, cluster = c("Year", "naics_3"))
d_mod4 <- feols(tcr ~ davg|Year + naics_3, odi_plant, cluster = c("Year", "naics_3"))

d_mod5 <- feols(tcr ~ log(fdi_tot)*davg, odi_plant, cluster = c("Year", "naics_3"))
d_mod6 <- feols(tcr ~ log(fdi_tot)*davg|Year, odi_plant, cluster = c("Year", "naics_3"))
d_mod7 <- feols(tcr ~ log(fdi_tot)*davg|naics_3, odi_plant, cluster = c("Year", "naics_3"))
d_mod8 <- feols(tcr ~ log(fdi_tot)*davg|Year + naics_3, odi_plant, cluster = c("Year", "naics_3"))

d_models <- list(d_mod1, d_mod2, d_mod3, d_mod4, d_mod4)
dint_models <- list(d_mod5, d_mod6, d_mod7, d_mod8)
```

```{r Interaction Regressions}
# mod1 <- feols(tcr ~ asinh(fdi)|Year, odi_ind, vcov = "twoway")
# mod2 <- feols(tcr ~ asinh(fdi)|Year + industry, odi_ind, vcov = "twoway")
# mod3 <- feols(tcr ~ asinh(fdi) + asinh(fdi)*inj_foreign, odi_source)
# mod4 <- feols(tcr ~ asinh(fdi) + asinh(fdi)*inj_foreign|Year, odi_source, vcov = "twoway")
# mod5 <- feols(tcr ~ asinh(fdi) + asinh(fdi)*inj_foreign|Year + naics_3, odi_source, vcov = "twoway")
```

```{r Summation Interaction}
s_mod1 <- feols(tcr ~ log(fdi_tot) + log(int_sum), odi_sum, cluster = c("Year", "naics_3"))
s_mod2 <- feols(tcr ~ log(fdi_tot) + log(int_sum)|Year, odi_sum, cluster = c("Year", "naics_3"))
s_mod3 <- feols(tcr ~ log(fdi_tot) + log(int_sum)|naics_3, odi_sum, cluster = c("Year", "naics_3"))
s_mod4 <- feols(tcr ~ log(fdi_tot) + log(int_sum)|Year + naics_3, odi_sum, cluster = c("Year", "naics_3"))

s_models <- list(s_mod1, s_mod2, s_mod3, s_mod4)
```

```{r FDI-exposed}
# e_mod1 <- feols(tcr ~ exposed*log(weight_avg) - exposed - log(weight_avg)|Year + industry.y, odi_ind)
# e_mod2 <- feols(tcr ~ exposed*log(weight_avg_l1), odi_ind)
# e_mod3 <- feols(tcr ~ exposed*log(weight_avg_l2), odi_ind)
# e_mod4 <- feols(tcr ~ exposed*log(weight_avg_l3), odi_ind)
# e_mod5 <- feols(tcr ~ exposed*log(weight_avg_l4), odi_ind)

e_mod1 <- feols(tcr ~ exposed*log(weight_avg) - exposed - log(weight_avg)|Year + industry.y, odi_ind)
e_mod2 <- feols(tcr ~ exposed*log(weight_avg_l1) - exposed - log(weight_avg_l1)|Year + industry.y, odi_ind)
e_mod3 <- feols(tcr ~ exposed*log(weight_avg_l2)- exposed - log(weight_avg_l2)|Year + industry.y, odi_ind)
e_mod4 <- feols(tcr ~ exposed*log(weight_avg_l3)- exposed - log(weight_avg_l3)|Year + industry.y, odi_ind)
e_mod5 <- feols(tcr ~ exposed*log(weight_avg_l4)- exposed - log(weight_avg_l4)|Year + industry.y, odi_ind)

e_models <- list(e_mod1, e_mod2, e_mod3, e_mod4, e_mod5)
```
```{r Basic Aggregated Regs}
agg_basic <- ind_year %>%
  feols(tcr~log(fdi), cluster = c("NAICS"))

agg_basic_year <- ind_year %>%
  feols(tcr ~ log(fdi)|Year, cluster = c("NAICS"))

agg_basic_twoway <- ind_year %>%
  feols(tcr ~ log(fdi)|Year + NAICS, cluster = c('NAICS'))

agg_basic_regs <- list(agg_basic, agg_basic_year, agg_basic_twoway)
etable(agg_basic_regs)
```

```{r aggregated regs safety interaction: industry}
agg_ind <- ind_year %>%
  feols(tcr ~ safe_industry*log(fdi), cluster = c('NAICS'))

agg_ind_year <- ind_year %>%
  feols(tcr ~ safe_industry*log(fdi)|Year, cluster = c('NAICS'))

agg_ind_twoway <- ind_year %>%
  feols(tcr ~ safe_industry*log(fdi)|Year+NAICS, cluster = c('NAICS'))

# agg_model_state <- state_ind_year %>%
#   feols(tcr ~ safe*log(fdi), cluster = c('STATE','NAICS'))

agg_ind_regs <- list(agg_ind, agg_ind_year, agg_ind_twoway)

etable(agg_ind_regs)
```

```{r safety interaction: state-level}
agg_state <- state_ind_year %>%
  feols(tcr ~ safe_state*log(fdi), cluster = c('STATE','NAICS'))

agg_state_year <- state_ind_year %>%
  feols(tcr ~ safe_state*log(fdi)|Year, cluster = c('STATE','NAICS'))

agg_state_twoway <- state_ind_year %>%
  feols(tcr ~ safe_state*log(fdi)|Year+NAICS, cluster = c('STATE','NAICS'))

agg_state_threeway <- state_ind_year %>%
  feols(tcr ~ safe_state*log(fdi)|Year+NAICS+STATE, cluster = c('STATE','NAICS'))

agg_ind_state <- state_ind_year %>%
  feols(tcr ~ safe_state*safe_industry*log(fdi)|Year+NAICS+STATE, cluster = c('STATE', 'NAICS'))

etable(agg_ind_state)

agg_state_models <- list(agg_state, agg_state_year, agg_state_twoway, agg_state_threeway)

etable(agg_state_models)

```
```{r Basic regs with safety shares}
basic_shares <- ind_year %>%
  feols(tcr~safe_share*log(fdi_total), cluster = c('NAICS'))

basic_shares_time <- ind_year %>%
  feols(tcr~safe_share*log(fdi_total)|Year, cluster = c('NAICS'))

basic_shares_twoway <- ind_year %>%
  feols(tcr~safe_share + log(fdi_total)|Year + NAICS, cluster = c('NAICS'))

basic_shares_twoway_interaction <- ind_year %>%
  feols(tcr~safe_share*log(fdi_total)|Year + NAICS, cluster = c('NAICS'))

basic_shares_regs <- list(basic_shares, basic_shares_time, basic_shares_twoway, basic_shares_twoway_interaction)

etable(basic_shares_regs)
```


```{r Aggregated regs with safety shares:industry}
agg_ind_shares <- ind_year %>%
  feols(tcr ~ safe_industry*safe_share, cluster = c('NAICS'))

agg_ind_shares_year <- ind_year %>%
  feols(tcr ~ safe_industry*safe_share|Year, cluster = c('NAICS'))

agg_ind_shares_twoway <- ind_year %>%
  feols(tcr ~ safe_industry*safe_share + log(fdi_total)|Year+NAICS, cluster = c('NAICS'))

agg_ind_shares_fdi <- ind_year %>%
  feols(tcr ~ safe_industry*safe_share + log(fdi_total), cluster = c('NAICS'))

agg_ind_shares_year_fdi <- ind_year %>%
  feols(tcr ~ safe_industry*safe_share + log(fdi_total)|Year, cluster = c('NAICS'))

agg_ind_shares_twoway_fdi <- ind_year %>%
  feols(tcr ~ safe_industry*safe_share + log(fdi_total)*safe_share|Year+NAICS, cluster = c('NAICS'))

agg_ind_shares_models <- list(agg_ind_shares, agg_ind_shares_year, agg_ind_shares_twoway, agg_ind_shares_fdi, agg_ind_shares_year_fdi, agg_ind_shares_twoway_fdi)

etable(agg_ind_shares_models)
```

```{r Aggregated regs with safety shares:state}
agg_state_shares <- state_ind_year %>%
  feols(tcr ~ safe_state*safe_share, cluster = c('NAICS'))

agg_state_shares_year <- state_ind_year %>%
  feols(tcr ~ safe_state*safe_share|Year, cluster = c('NAICS'))

agg_state_shares_twoway <- state_ind_year %>%
  feols(tcr ~ safe_state*safe_share +log(fdi_total)|Year+NAICS+STATE, cluster = c('NAICS'))

agg_state_shares_fdi <- state_ind_year %>%
  feols(tcr ~ safe_state*safe_share + log(fdi_total), cluster = c('NAICS'))

agg_state_shares_year_fdi <- state_ind_year %>%
  feols(tcr ~ safe_state*safe_share + log(fdi_total)|Year, cluster = c('NAICS', 'STATE'))

agg_state_shares_twoway_fdi <- state_ind_year %>%
  feols(tcr ~ safe_state*safe_share + log(fdi_total)*safe_share|Year+NAICS+STATE, cluster = c('NAICS', 'STATE'))

agg_ind_state_share_twoway_fdi<- state_ind_year %>%
  feols(tcr ~ safe_state*safe_industry*safe_share + log(fdi_total)|Year+NAICS+STATE, cluster = c('NAICS', 'STATE'))

agg_state_shares_models <- list(agg_state_shares, agg_state_shares_year, agg_state_shares_twoway, agg_state_shares_fdi, agg_state_shares_year_fdi, agg_state_shares_twoway_fdi)

etable(agg_state_shares_models)
```
#####Tables

```{r Global Table Stuff}
gf_omitted <- "R2 Within|R2 P|Log|AIC|BIC|Std"
star_map = c('*' = .1, '**' = 0.05, '***' = 0.01)
gm <- tribble(~raw, ~clean, ~fmt,
              "FE: Year", "Year FE", "%.4f",
              "FE: NAICS", "Industry FE", "%.4f",
              "FE: STATE", "State FE", "%.4f",
              "nobs", "Observations", "%.0f",
              "r.squared", "R2", "%.2f")

cm <- c("(Intercept)" = "Intercept",
        "log(fdi)" = "$ln(FDI)$",
        "log(fdi_total)" = "ln(FDI)",
        "safe_industry" = "$SafeIndustry$",
        "safe_industry:log(fdi)" = "$SafeIndustry \\times ln(FDI)$",
        "safe_state" = "$SafeState$",
        "safe_state:log(fdi)" = "$SafeState \\times ln(FDI)$",
        "safe_share" = "$Share^{Safe FDI}$",
        "safe_share:log(fdi)" = "$ln(FDI) \\times Share^{Safe FDI}$",
        "safe_industry:safe_share" = "$SafeIndustry \\times Share^{Safe FDI}$",
        "safe_state:safe_share" = "$SafeState \\times Share^{Safe FDI}$",
        "safe_state:safe_industry" = "$SafeIndustry \\times SafeState$",
        "safe_state:safe_industry:log(fdi)" = "$SafeIndustry \\times SafeState \\times ln(FDI)$",
        "safe_state:safe_industry:safe_share" = "$SafeIndustry \\times SafeState \\times Share^{Safe FDI}$")

```

```{r Basic regs Table}
fn <- "Standard errors clustered at the industry level."

tab_basic_regs <- modelsummary(agg_basic_regs,
                               stars = star_map,
                               coef_map = cm,
                               title = "Dependent variable: Total Case Rate (TCR)",
                               gof_map = gm,
                               output = "latex",
                               escape = FALSE,
                               fmt = "%.4f") %>%
  add_footnote(fn, threeparttable = TRUE)

kableExtra::save_kable(tab_basic_regs, file = "../Output/reg_tables/basic_regs.tex")
```

```{r Industry-level safety interaction table}
fn <- "Standard errors clustered at the industry level."

tab_agg_ind <- modelsummary(agg_ind_regs,
                               stars = star_map,
                               coef_map = cm,
                               title = "Dependent variable: Total Case Rate (TCR)",
                               gof_map = gm,
                               output = "latex",
                               escape = FALSE,
                               fmt = "%.4f") %>%
  add_footnote(fn, threeparttable = TRUE)

kableExtra::save_kable(tab_agg_ind, file = "../Output/reg_tables/agg_industry_safety.tex")
```

```{r State-level safety interaction table}
fn <- "Standard errors clustered at the industry-state level."

agg_state_tab <- modelsummary(agg_state_models,
                               stars = star_map,
                               coef_map = cm,
                               title = "Dependent variable: Total Case Rate (TCR)",
                               gof_map = gm,
                               output = "latex",
                               escape = FALSE,
                               fmt = "%.4f") %>%
  add_footnote(fn, threeparttable = TRUE)

kableExtra::save_kable(agg_state_tab, file = "../Output/reg_tables/agg_state_safety.tex")
```

```{r full safety interaction table}
interaction_models <- list(agg_ind_year, agg_ind_twoway, agg_state_year, agg_state_twoway, agg_state_threeway, agg_ind_state)

fn <- "Standard errors clustered at the industry level columns (1) and (2), clustered at the industry-state level for columns (3) through (6)."

agg_interaction_tab <- modelsummary(interaction_models,
                               stars = star_map,
                               coef_map = cm,
                               title = "Dependent variable: Total Case Rate (TCR)",
                               gof_map = gm,
                               output = "latex",
                               escape = FALSE,
                               fmt = "%.4f") %>%
  add_header_above(c(" " = 1, "Industry-Level" = 2, "State-Level" = 4)) %>%
  add_footnote(fn, threeparttable = TRUE)

kableExtra::save_kable(agg_interaction_tab, file = "../Output/reg_tables/agg_interaction.tex")

etable(interaction_models)

```

```{r Industry-level shares table}
fn <- "Standard errors clustered at the industry level."

agg_ind_shares_tab <- modelsummary(agg_ind_shares_models,
                               stars = star_map,
                               coef_map = cm,
                               title = "Dependent variable: Total Case Rate (TCR)",
                               gof_map = gm,
                               output = "latex",
                               escape = FALSE,
                               fmt = "%.4f") %>%
  add_footnote(fn, threeparttable = TRUE)

kableExtra::save_kable(agg_ind_shares_tab, file = "../Output/reg_tables/industry_safety_shares.tex")
```

```{r State-level shares table}
fn <- "Standard errors clustered at the industry level."

agg_state_shares_tab <- modelsummary(agg_state_shares_models,
                               stars = star_map,
                               coef_map = cm,
                               title = "Dependent variable: Total Case Rate (TCR)",
                               gof_map = gm,
                               output = "latex",
                               escape = FALSE,
                               fmt = "%.4f") %>%
  add_footnote(fn, threeparttable = TRUE)

kableExtra::save_kable(agg_state_shares_tab, file = "../Output/reg_tables/state_safety_shares.tex")
```

```{r Full shares table}
# shares_models <- list(basic_shares_twoway, basic_shares_twoway_interaction, agg_ind_shares_twoway, agg_ind_shares_twoway_fdi,agg_state_shares_twoway, agg_state_shares_twoway_fdi, agg_ind_state_share_twoway_fdi)

shares_models <- list(basic_shares_twoway, agg_ind_shares_twoway, agg_state_shares_twoway, agg_ind_state_share_twoway_fdi)

fn <- "Standard errors clustered at the industry level columns (1) through (3), clustered at the industry-state level for column (4)."

agg_state_shares_tab <- modelsummary(shares_models,
                               stars = star_map,
                               coef_map = cm,
                               title = "Dependent variable: Total Case Rate (TCR)",
                               gof_map = gm,
                               output = "latex",
                               escape = FALSE,
                               fmt = "%.4f") %>%
  add_header_above(c(" " = 1, "Industry-Level" = 2, "State-Level" = 2)) %>%
  add_footnote(fn, threeparttable = TRUE)

kableExtra::save_kable(agg_state_shares_tab, file = "../Output/reg_tables/shares_table.tex")

etable(shares_models)
```


```{r See all results}

modelsummary(ind_models,
             stars = TRUE,
             output = "markdown")

modelsummary(wa_models,
             stars = TRUE,
             output = "markdown")

modelsummary(d_models,
             stars = TRUE,
             output = "markdown")

modelsummary(s_models,
             stars = TRUE,
             output = "markdown")

modelsummary(e_models,
             stars = TRUE,
             output = "markdown")

modelsummary(lmods,
             stars = TRUE,
             output = "markdown")

modelsummary(lwa_mods,
             stars = TRUE,
             output = "markdown")

```

```{r Figures}
fdi_all <- fdi %>%
  filter(title_2 == "All Industries Total")

fdi_source <- ggplot(fdi, aes(x=Year, y=fdi)) +
  geom_smooth(se=FALSE, aes(color = Country))

show(fdi_source)
```

```{r Threshold Regressions}
# mod1 <- feols(tcr ~ asinh(fdi)|Year, odi_ind, vcov = "twoway")
# mod2 <- feols(tcr ~ asinh(fdi)|Year + industry, odi_ind, vcov = "twoway")
# mod3 <- feols(tcr ~ asinh(fdi_safe_us) + asinh(fdi_unsafe_us)|Year, odi_fdi_safety, vcov = "twoway")
# mod4 <- feols(tcr ~ asinh(fdi_safe_us) + asinh(fdi_unsafe_us)|Year + naics_3, odi_fdi_safety, vcov = "twoway")
# mod5 <- feols(tcr ~ asinh(fdi_safe_ind) + asinh(fdi_unsafe_ind)|Year, odi_fdi_safety, vcov = "twoway")
# mod6 <- feols(tcr ~ asinh(fdi_safe_ind) + asinh(fdi_unsafe_ind)|Year + naics_3, odi_fdi_safety, vcov = "twoway")
# mod7 <- feols(tcr ~ asinh(fdi_safe_plant) + asinh(fdi_unsafe_plant)|Year, odi_fdi_safety, vcov = "twoway")
# mod8 <- feols(tcr ~ asinh(fdi_safe_plant) + asinh(fdi_unsafe_plant)|Year + naics_3, odi_fdi_safety, vcov = "twoway")
# 
# models <- list(mod1, mod2, mod3, mod4, mod5, mod6, mod7, mod8)
```

```{r Table 2}
# cm <- c("asinh(fdi)" = "$FDI^{total}$", "asinh(fdi_safe_us)" = "$FDI^{safe}$", "asinh(fdi_unsafe_us)" = "$FDI^{unsafe}$", "asinh(fdi_safe_ind)" = "$FDI^{safe}$", "asinh(fdi_unsafe_ind)" = "$FDI^{unsafe}$", "asinh(fdi_safe_plant)" = "$FDI^{safe}$", "asinh(fdi_unsafe_plant)" = "$FDI^{unsafe}$")
# 
# cap <- "Dependent variable: Total Case Rate (TCR)"
# 
# fn <- "Time fixed effects are included in all specifications. All independent variables are the inverse hyperbolic sine of the inward FDI position in the industry. The columns United States, Industry, and Plant represent different thresholds used to determine whether FDI is coming from safe or unsafe sources. Robust standard errors are clustered at the industry-year level."
# 
# gm <- tribble(~raw, ~clean, ~fmt,
#               "FE: naics_3", "Industry FE", "%.4f",
#               "FE: industry", "Industry FE", "%.4f",
#               "nobs", "Observations", "%.0f",
#               "r.squared", "R2", "%.2f")
# 
# 
# 
# tab <- modelsummary(models,
#              stars = TRUE,
#              coef_map = cm,
#              title = cap,
#              gof_omit = "R2 Within|R2 P|Log|AIC|BIC|Std|Year",
#              gof_map = gm,
#              coef_omit = "Intercept",
#              output = "latex",
#              escape = FALSE,
#              fmt = "%.4f") %>%
#   add_header_above(c(" " = 3, "United States" = 2, "Industry" = 2, "Plant" = 2)) %>%
#   add_footnote(fn, threeparttable = TRUE)
# 
# kableExtra::save_kable(tab, file = "../Output/table1.tex")
# 
# # modelsummary(models,
# #              stars = TRUE,
# #              gof_omit = "R2 Within|R2 P|Log|AIC|BIC|Std",
# #              output = "latex")
```

```{r Scatter Plots}
scatter_us <- ggplot(odi_fdi_safety, aes(x = fdi_unsafe_us, y = tcr)) + geom_point() + ylim(0,300) + geom_smooth(method = "lm")

scatter_ind <- ggplot(odi_fdi_safety, aes(x = fdi_unsafe_ind, y = tcr)) + geom_point() + ylim(0,300) + geom_smooth(method = "lm")

scatter_u_plant <- ggplot(odi_fdi_safety, aes(x = fdi_unsafe_plant, y = tcr)) + geom_point() + ylim(0,100) + xlim(0,100000) + geom_smooth(method = "lm")

scatter_s_plant <- ggplot(odi_fdi_safety, aes(x = fdi_safe_plant, y = tcr)) + geom_point(size = 1) + geom_point(aes(fdi_unsafe_plant, tcr), color = "red", size = 1) +  ylim(0,100) + xlim(0,100000) + geom_smooth(method = "lm")

# scatter_fdi <- ggplot(odi_ind, aes(x = fdi, y = tcr)) + geom_point(position = "dodge") + ylim(0,100) + xlim(0,100000) + geom_smooth(method = "lm")

show(scatter_s_plant)
```



```{r Test code}
int_breaks <- function(x, n = 5) {
  l <- pretty(x, n)
  l[abs(l %% 1) < .Machine$double.eps ^ 0.5] 
}

test <- odi_ind %>%
  group_by(Year) %>%
  summarise(
    inj = mean(tcr, na.rm = TRUE),
    fdi = mean(fdi, na.rm=TRUE)
  )

ggplot(test, aes(x = Year, y = fdi)) + geom_smooth(se=FALSE) + scale_x_continuous(breaks = int_breaks)
```














